export const IMAGE = {
  //Tab
  Home: require("../../assets/icons/Home.png"),
  Messages: require("../../assets/icons/Messages.png"),
  Trade: require("../../assets/icons/Trade.png"),
  More: require("../../assets/icons/More.png"),

  chatgpt: require("../../assets/icons/chatgpt.png"),
  compass: require("../../assets/icons/compass.png"),
  play: require("../../assets/icons/play.png"),
  viewmore: require("../../assets/icons/view-more.png"),
  right: require("../../assets/icons/right.png"),
  Logo: require("../../assets/icons/Logo.png"),
  LogoRaw: require("../../assets/icons/LogoRaw.png"),

  //Welcome
  World: require("../../assets/icons/World.png"),
  RightArrow: require("../../assets/icons/RightArrow.png"),

  //Dashboard
  MobileSupport: require("../../assets/images/mobile-Support.png"),
  Articles: require("../../assets/images/Articles.png"),
  Calander: require("../../assets/images/Calander.png"),
  CaseDashboards: require("../../assets/images/CaseDashboards.png"),
  Downloads: require("../../assets/images/Downloads.png"),
  FeaturedContent: require("../../assets/images/FeaturedContent.png"),
  Importantnotices: require("../../assets/images/Importantnotices.png"),
  TechReviewComplete: require("../../assets/images/TechReviewComplete.png"),
  Inputs: require("../../assets/images/Inputs.png"),
  Produce: require("../../assets/images/Produce.png"),
  Processed: require("../../assets/images/Processed.png"),
  Transport: require("../../assets/images/Transport.png"),
  Warehouse: require("../../assets/images/Warehouse.png"),
  Finance: require("../../assets/images/Finance.png"),
  Insurance: require("../../assets/images/Insurance.png"),
  Search : require("../../assets/images/search.png"),
  RightArrow: require("../../assets/images/RightArrow.png"),
  Fields: require("../../assets/images/Fields.png"),
  Vegetable: require("../../assets/images/Vegetable.png"),
  Fruits: require("../../assets/images/fruits.png"),
  Leafy : require("../../assets/images/leafy.png"),
  Cashcrop : require("../../assets/images/cashcrop.png"),
  OilSeed: require("../../assets/images/oilseed.png"),
  SeedTreatment: require("../../assets/images/seedTreatment.png"),
  Medicinal: require("../../assets/images/medicinal.png"),
  Saplings: require("../../assets/images/saplings.png"),
  Plantation: require("../../assets/images/4327458.png"),
  Seeds: require("../../assets/images/seeds.png"),
  CatSeeds: require("../../assets/images/CatSeeds.png"),
  CatFertilizer: require("../../assets/images/CatFertilizer.png"),
  CatPesticides: require("../../assets/images/CatPesticides.png"),
  CatSeeds : require("../../assets/images/CatSeeds.png"),
  CatOther: require("../../assets/images/CatOther.png"),
  CatImplant: require("../../assets/images/CatImplant.png"),
  Up: require("../../assets/images/up.png"),
  Down: require("../../assets/images/down.png"),
};
